<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="maa" name="Default test" tests="1" failures="0" timestamp="31 Jul 2018 23:23:02 GMT" time="0.178" errors="0">
  <testcase name="@BeforeClass ConfigBC" time="0.0" classname="com.actitime.customertest.CustomerTest">
    <failure type="java.io.FileNotFoundException" message=".\TestData\TestData.properties (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: .\TestData\TestData.properties (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.actitime.genericlib.FileUtils.getPropertiesFileObj(FileUtils.java:19)
	at com.actitime.genericlib.BaseClass.ConfigBC(BaseClass.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeClass ConfigBC -->
  <testcase name="@BeforeMethod ConfigBM" time="0.0" classname="com.actitime.customertest.CustomerTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod ConfigBM -->
  <testcase name="@AfterMethod ConfigAM" time="0.0" classname="com.actitime.customertest.CustomerTest">
    <skipped/>
  </testcase> <!-- @AfterMethod ConfigAM -->
  <testcase name="@AfterClass ConfigAC" time="0.0" classname="com.actitime.customertest.CustomerTest">
    <skipped/>
  </testcase> <!-- @AfterClass ConfigAC -->
  <testcase name="creatCustomerTest" time="0.006" classname="com.actitime.customertest.CustomerTest">
    <skipped/>
  </testcase> <!-- creatCustomerTest -->
</testsuite> <!-- Default test -->
